
package ventanas;

import domain.Ecuacion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/** @author carlos david*/
public class VentanaPrincipal extends javax.swing.JFrame {

    String lista;
    private String ecuacion = "";   //aqui se almacenara lo que se escriba;

    public VentanaPrincipal() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.textoPantalla.setText("0");

    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/IconoCalculadora.png"));
        return retValue;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        PANTALLA = new javax.swing.JPanel();
        textoPantalla = new javax.swing.JLabel();
        listaPantalla = new javax.swing.JLabel();
        numero1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        ButtonSumar = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(0, 51, 92));
        panelPrincipal.setToolTipText("");
        panelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelPrincipalKeyPressed(evt);
            }
        });
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANTALLA.setBackground(new java.awt.Color(47, 152, 255));
        PANTALLA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 121, 204), 5));
        PANTALLA.setForeground(new java.awt.Color(37, 121, 204));
        PANTALLA.setToolTipText("");
        PANTALLA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PANTALLAKeyPressed(evt);
            }
        });

        textoPantalla.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        textoPantalla.setForeground(new java.awt.Color(250, 249, 249));
        textoPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoPantalla.setText("Bienvenido!!");

        listaPantalla.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        listaPantalla.setForeground(new java.awt.Color(255, 255, 255));
        listaPantalla.setText("0");

        javax.swing.GroupLayout PANTALLALayout = new javax.swing.GroupLayout(PANTALLA);
        PANTALLA.setLayout(PANTALLALayout);
        PANTALLALayout.setHorizontalGroup(
            PANTALLALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANTALLALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANTALLALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PANTALLALayout.setVerticalGroup(
            PANTALLALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANTALLALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPrincipal.add(PANTALLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        numero1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numero1.setText("1");
        numero1.setFocusable(false);
        numero1.setPreferredSize(new java.awt.Dimension(45, 45));
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 197, 60, -1));

        jButton2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.setFocusable(false);
        jButton2.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 197, 60, -1));

        jButton4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton4.setText("3");
        jButton4.setFocusable(false);
        jButton4.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 197, 60, -1));

        jButton5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton5.setText("4");
        jButton5.setFocusable(false);
        jButton5.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 249, 60, -1));

        jButton6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton6.setText("7");
        jButton6.setFocusable(false);
        jButton6.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 301, 60, -1));

        jButton7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton7.setText("6");
        jButton7.setFocusable(false);
        jButton7.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 249, 60, -1));

        jButton8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton8.setText("5");
        jButton8.setFocusable(false);
        jButton8.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 249, 60, -1));

        jButton9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton9.setText("8");
        jButton9.setFocusable(false);
        jButton9.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 301, 60, -1));

        jButton10.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton10.setText("9");
        jButton10.setFocusable(false);
        jButton10.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 301, 60, -1));

        jButton11.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton11.setText("0");
        jButton11.setFocusable(false);
        jButton11.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 353, 60, -1));

        jButton12.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton12.setText("10");
        jButton12.setFocusable(false);
        jButton12.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 353, 60, -1));

        jButton14.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButton14.setText("000");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton14.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 353, 60, -1));

        btnBorrar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBorrar.setFocusable(false);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setPreferredSize(new java.awt.Dimension(45, 45));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 197, 87, -1));

        jButton16.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jButton16.setText("×");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton16.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 353, 87, -1));

        ButtonSumar.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        ButtonSumar.setText("+");
        ButtonSumar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonSumar.setFocusable(false);
        ButtonSumar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ButtonSumar.setPreferredSize(new java.awt.Dimension(45, 45));
        ButtonSumar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ButtonSumar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumarActionPerformed(evt);
            }
        });
        panelPrincipal.add(ButtonSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 249, 87, -1));

        jButton18.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jButton18.setText("-");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton18.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 301, 87, -1));

        jButton19.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jButton19.setText("÷");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton19.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 405, 87, -1));

        jButton20.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButton20.setText("    ?");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 470, 60, -1));

        calcular.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        calcular.setText("=");
        calcular.setFocusable(false);
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        panelPrincipal.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 405, 127, 45));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("@Carlos olivera 12/12/2021");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 551, -1, -1));

        jButton13.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jButton13.setText(".");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 405, 60, -1));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrar() {
        textoPantalla.setText(this.ecuacion);
    }

    private void introducir(String a) {        
        this.ecuacion += a;
        this.textoPantalla.setText(this.ecuacion);
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        introducir("10");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        introducir("1");
    }//GEN-LAST:event_numero1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        introducir("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        introducir("3");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        introducir("4");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        introducir("5");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        introducir("6");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        introducir("7");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        introducir("8");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        introducir("9");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        borrar();
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    private void borrar(){
        if(this.ecuacion.isEmpty()){
            return;
        }
        this.ecuacion = this.ecuacion.substring(0, this.ecuacion.length()-1);
        mostrar();
    }
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        introducir("000");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        signoPor();
    }//GEN-LAST:event_jButton16ActionPerformed
    
    private void signoPor(){
        String t = this.textoPantalla.getText();
        if(t.isEmpty()){
            return;
        }
        if(t.endsWith("*")){
            return;
        }
        if(t.endsWith("+") || t.endsWith("-") || t.endsWith("/")){
            t = t.substring(0, t.length()-1);

        }
        t += "*";
        this.ecuacion = t;
        mostrar();
    }
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        introducir("0");
    }//GEN-LAST:event_jButton11ActionPerformed



    private void ButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumarActionPerformed
        signoMas();
    }//GEN-LAST:event_ButtonSumarActionPerformed
    
    private void signoMas(){
        String t = this.textoPantalla.getText();
         
        if(t.isEmpty()){
            return;
        }
        if(t.endsWith("-")|| t.endsWith("/")|| t.endsWith("*")){
            t = t.substring(0, t.length()-1);
        }else if(t.endsWith("+")){
            return;
        }
        t += "+";
        this.ecuacion = t;
        mostrar();
    }

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        signoMenos();
    }//GEN-LAST:event_jButton18ActionPerformed
    
    private void signoMenos(){
        String t = this.textoPantalla.getText();

        if(t.endsWith("-")){
            return;
        }        
        if(t.endsWith("+")){
            t = t.substring(0, t.length()-1);
        }
        t += "-";
        this.ecuacion = t;
        mostrar();
    }
    
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        signoEntre();
    }//GEN-LAST:event_jButton19ActionPerformed
    
    private void signoEntre(){
        String t = this.textoPantalla.getText();
        if(t.isEmpty()){
            return;
        }if(t.endsWith("/")){
            return;
        }         
        if(t.endsWith("+") || t.endsWith("-")|| t.endsWith("*")){
            t = t.substring(0, t.length()-1);

        }
        t += "/";
        this.ecuacion = t;  
        mostrar();
    }
    
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        JOptionPane.showMessageDialog(this, "Creada por Carlos david Olivera, 2023\nEmpezada en dic 2021 terminada ene 2023", "Pa que sepas",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        calcular();
    }//GEN-LAST:event_calcularActionPerformed
    
    private void calcular(){
        if(this.ecuacion.isEmpty()){
            return;
        }
        try{
            Ecuacion ec = new Ecuacion(this.ecuacion);
            String res = String.valueOf(ec.getResultado());
            this.listaPantalla.setText(this.ecuacion += " =");
            if(res.endsWith(".0")){
                res = res.substring(0, res.length()-2);
            }

            this.ecuacion = String.valueOf(res);
            mostrar();
            this.ecuacion = "";
        }catch(java.lang.NumberFormatException e){
            this.textoPantalla.setText("ESCRIBA BIEN OMBE");
            System.out.println(e);
        }catch(ArithmeticException e){
            this.textoPantalla.setText("ERROR MATEMATICO");
            System.out.println(e);
       }
        
    }
    
    private void panelPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPrincipalKeyPressed


        
    }//GEN-LAST:event_panelPrincipalKeyPressed

    private void PANTALLAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PANTALLAKeyPressed


    }//GEN-LAST:event_PANTALLAKeyPressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        signoPunto();
    }//GEN-LAST:event_jButton13ActionPerformed
    
    private void signoPunto(){
        if(this.ecuacion.isEmpty()){
            this.ecuacion = "0.";
            mostrar();
        }
        if(this.ecuacion.charAt(this.ecuacion.length()-1) != '.'){
            
            this.introducir("."); 
        }     
    }
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        switch(evt.getKeyCode()){
            case KeyEvent.VK_0, KeyEvent.VK_NUMPAD0 -> this.introducir("0");
            case KeyEvent.VK_1, KeyEvent.VK_NUMPAD1 -> this.introducir("1");
            case KeyEvent.VK_2, KeyEvent.VK_NUMPAD2 -> this.introducir("2");
            case KeyEvent.VK_3, KeyEvent.VK_NUMPAD3 -> this.introducir("3");
            case KeyEvent.VK_4, KeyEvent.VK_NUMPAD4 -> this.introducir("4");
            case KeyEvent.VK_5, KeyEvent.VK_NUMPAD5 -> this.introducir("5");
            case KeyEvent.VK_6, KeyEvent.VK_NUMPAD6 -> this.introducir("6");
            case KeyEvent.VK_7, KeyEvent.VK_NUMPAD7 -> this.introducir("7");
            case KeyEvent.VK_8, KeyEvent.VK_NUMPAD8 -> this.introducir("8");
            case KeyEvent.VK_9, KeyEvent.VK_NUMPAD9 -> this.introducir("9");
            case KeyEvent.VK_PLUS, KeyEvent.VK_ADD -> signoMas();
            case KeyEvent.VK_SUBTRACT, KeyEvent.VK_MINUS -> signoMenos();
            case KeyEvent.VK_MULTIPLY, KeyEvent.VK_ASTERISK-> signoPor(); 
            case KeyEvent.VK_DIVIDE, KeyEvent.VK_SLASH -> signoEntre();
            case KeyEvent.VK_ENTER -> calcular();
            case KeyEvent.VK_PERIOD, KeyEvent.VK_DECIMAL -> signoPunto();
            case KeyEvent.VK_BACK_SPACE -> borrar();
            
        }
        
    }//GEN-LAST:event_formKeyPressed


    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSumar;
    private javax.swing.JPanel PANTALLA;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton calcular;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel listaPantalla;
    private javax.swing.JButton numero1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel textoPantalla;
    // End of variables declaration//GEN-END:variables



}
